#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: true

# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyStart: source/_data/post-body-start.njk
  postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  #style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

darkmode: false


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg
  # android_manifest: /manifest.json
  ms_browserconfig: /images/browserconfig.xml

# Custom Logo (Warning: Do not support scheme Mist)
custom_logo: #/uploads/custom-logo.jpg

creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-nc-sa
  # Available values: big | small
  size: small
  sidebar: true
  post: true
  language: deed.zh

open_graph:
  enable: true
  # Add pairs each line to customize
  options:
    type: blog


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  # categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  # schedule: /schedule/ || fa fa-calendar
  # sitemap: /sitemap.xml || fa fa-sitemap
  # commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: false


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left # left or right
  # width: 300 # Muse and Mist schemes default to 320, Pisces and Gemini default to 240
  display: post # post, always, hide or remove
  padding: 18
  offset: 12

avatar:
  url: /images/avatar.png
  rounded: true
  rotated: false

# Posts / Categories / Tags in sidebar.
site_state: true

social:
  GitHub: https://github.com/ProxyRule || fab fa-github
  # E-Mail: mailto:yourname@gmail.com || fa fa-envelope
  # Weibo: https://weibo.com/yourname || fab fa-weibo
  # Twitter: https://twitter.com/yourname || fab fa-twitter
  # FB Page: https://www.facebook.com/yourname || fab fa-facebook
  # StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
  YouTube: https://www.youtube.com/channel/UCuwhJBqfSTZIVhkFiTsHrgw || fab fa-youtube
  # Instagram: https://instagram.com/yourname || fab fa-instagram
  # Skype: skype:yourname?call|chat || fab fa-skype
  RSS: /atom.xml || fa fa-rss

social_icons:
  enable: true
  icons_only: true
  transition: false

# Blog rolls
links_settings:
  icon: fa fa-globe
  title: Links
  # Available values: block | inline
  layout: block

links:
  # Title1: https://example1.com/
  # Title2: https://example2.com/

toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2016
  icon:
    name: fa fa-heart
    animated: false
    color: "#ff0000"
  copyright:
  powered: true
  beian:
    enable: false
    icp:
    gongan_id:
    gongan_num:
    gongan_icon_url:


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

# Automatically excerpt description in homepage as preamble text.
excerpt_description: false

post_meta:
  item_text: true # By default NexT shows the description text of post meta.
  created_at: true
  updated_at: # Hexo config updated_option
    enable: true
    another_day: true
  categories: false

symbols_count_time:
  separated_meta: true
  item_text_total: false

tag_icon: true

reward_settings:
  # If true, a donate button will be displayed in every article by default.
  enable: false
  animation: false
  comment: Buy me a coffee

reward:
  # wechatpay: /images/wechatpay.jpg
  # alipay: /images/alipay.jpg
  # paypal: /images/paypal.png
  # bitcoin: /images/bitcoin.png

follow_me:
  # Twitter: https://twitter.com/username || fab fa-twitter
  # Telegram: https://t.me/channel_name || fab fa-telegram
  # WeChat: /images/wechat_channel.jpg || fab fa-weixin
  # Zhihu: https://www.zhihu.com/people/username || fab fa-zhihu
  # RSS: /atom.xml || fa fa-rss

post_edit:
  enable: false
  url: https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name/ # Link for view source
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/ # Link for fork & edit

post_navigation: left # Available values: left | right | false


# ============================================================= #
# =================== Custom Page Settings ==================== #
# ============================================================= #

tag_generator: # Hexo plugin hexo-generator-tag
  enable_index_page: false

tagcloud:
  min: 12 # Minimun font size in px
  max: 30 # Maxium font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

preconnect: true

text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify

mobile_layout_economy: true

theme_color:
  light: "#222"
  dark: "#222"

# Override browsers' default behavior.
body_scrollbar:
  # Place the scrollbar over the content.
  overlay: false
  # Present the scrollbar even if the content is not overflowing.
  stable: false

codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: default
    dark: tomorrow-night-bright
  prism:
    light: prism-solarizedlight
    dark: prism-tomorrow
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Available values: default | flat | mac
    style: flat

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true

reading_progress:
  enable: false
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 2px

bookmark:
  enable: false
  # Customize the color of the bookmark.
  color: "#222"
  # If auto, save the reading progress when closing the page or clicking the bookmark-icon.
  # If manual, only save it by clicking the bookmark-icon.
  save: auto

github_banner:
  enable: false
  permalink: https://github.com/yourname
  title: Follow me on GitHub

font:
  # Use custom fonts families or not.
  # Depended options: `external` and `family`.
  enable: false

  # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
  host:

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Monda
    size: 1.125

  # Font settings for site title (.site-title).
  title:
    external: true
    family: Lobster Two
    size:

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Amita
    size:

  # Font settings for posts (.post-body).
  posts:
    external: true
    family: Montserrat

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: PT Mono


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: false

google_site_verification: 
bing_site_verification: 

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: false


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: modern
  icons: true
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

pdf:
  enable: true
  # Default height
  height: 500px

tabs:
  # Make the nav bar of tabs with long content stick to the top.
  sticky: true
  transition:
    tabs: false
    labels: true

# Mermaid tag
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme:
    light: default
    dark: dark

# WaveDrom tag
wavedrom:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

# Math Formulas Render Support
math:
  # Default (false) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in front-matter.
  # If you set it to true, it will load mathjax / katex script EVERY PAGE.
  every_page: false

  mathjax:
    enable: false
    # Available values: none | ams | all
    tags: none

  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false

pjax: false

fancybox: false
mediumzoom: true

lazyload: false

pangu: true

quicklink:
  enable: true
  home: true
  archive: true
  delay: true
  timeout: 3000
  priority: true

# Use Animate.css to animate everything.
# For more information: https://animate.style
motion:
  enable: false
  async: false
  transition:
    # All available Transition variants: https://theme-next.js.org/animate/
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    # Only for Pisces | Gemini.
    sidebar: fadeInUp

pace:
  enable: false
  color: orange
  theme: minimal


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances | isso
  active:
  # Setting `true` means remembering the comment system selected by the visitor
  storage: true
  # Lazyload all comment systems.
  lazyload: true
  # Modify icons and texts for any style, here are some examples
  nav:
    #disqus:
    #  text: Load Disqus
    #  order: -1
    #gitalk:
    #  order: -2

# Utterances
# For more information: https://utteranc.es
utterances:
  enable: true
  repo: ProxyRule/youtube # Github repository owner and name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# Cloudflare Web Analytics
cloudflare_analytics: 6a76903e336e4cc58924a3300de1ad69

# Umami Analytics
umami:
  enable: true
  script_url: https://umami.shuaizheng.net/script.js # https://umami.example.com/script.js
  website_id: 79f168a7-944e-4a85-8571-26a94d508d3e # <your website id>
  host_url: # <your umami site url>


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false


# ============================================================= #
# ======================= CDN Settings ======================== #
# ============================================================= #

vendors:
  # The CDN provider of NexT internal scripts.
  # Available values: local | jsdelivr | unpkg | cdnjs | custom
  # Warning: If you are using the latest master branch of NexT, please set `internal: local`
  internal: local
  # The default CDN provider of third-party plugins.
  # Available values: local | jsdelivr | unpkg | cdnjs | custom
  # Dependencies for `plugins: local`: https://github.com/next-theme/plugins
  plugins: cdnjs
  # Custom CDN URL
  # For example:
  # custom_cdn_url: https://cdn.jsdelivr.net/npm/${npm_name}@${version}/${minified}
  # custom_cdn_url: https://cdnjs.cloudflare.com/ajax/libs/${cdnjs_name}/${version}/${cdnjs_file}
  custom_cdn_url:
