#################################################################
###################### Hexo Configuration #######################
#################################################################

# Site
title: 知识参考
subtitle: 
description: YouTube 频道配套网站
keywords: "Clash Tutorial, Docker Tutorial, Network Proxy, Website Development, Cryptocurrency, Personal Finance"
author: ZS.FYI
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://zs.fyi # or http://example.com/child
root: / # or /child/
permalink: archives/:title.html
permalink_defaults: 
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - browserconfig.xml
  - CNAME
  - robots.txt
  - site.webmanifest

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  exclude_languages:
    - mermaid
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
index_generator:
  path: '' # Root path for your blogs index page. (default = '')
  per_page: 5 # Posts displayed per page. (0 = disable pagination)
  order_by: -date # Posts order. (Order by date descending by default)
  pagination_dir: page # URL format for pagination

# Category & Tag
default_category: uncategorized
category_map: 
tag_map: 

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

# Pagination
per_page: 10 # Set per_page to 0 to disable pagination
pagination_dir: page

# Extensions
theme: next
theme_config: 
deploy: 
meta_generator: true

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  gfm: true
  lazyload: true

search:
  path: search.xml
  field: post
  content: true
  format: html

# Include / Exclude Files or Folders
## include and exclude options only apply to the source/ folder
## ignore option applies to all folders
include: 
exclude: 
ignore: 
